# Import Libraries

In [ ]:
import pandas as pd
from pandas import Series, DataFrame
import matplotlib.pyplot as plt
import seaborn as sns
import datetime as dt
import numpy as np

In [ ]:
!pip install sqlalchemy psycopg2

Requirement already satisfied: sqlalchemy in c:\anaconda3\lib\site-packages (1.3.13)
Requirement already satisfied: psycopg2 in c:\anaconda3\lib\site-packages (2.9.3)

WARNING: Ignoring invalid distribution -ip (c:\anaconda3\lib\site-packages)
WARNING: Ignoring invalid distribution -ip (c:\anaconda3\lib\site-packages)
WARNING: Ignoring invalid distribution -ip (c:\anaconda3\lib\site-packages)
WARNING: Ignoring invalid distribution -ip (c:\anaconda3\lib\site-packages)
WARNING: Ignoring invalid distribution -ip (c:\anaconda3\lib\site-packages)
WARNING: Ignoring invalid distribution -ip (c:\anaconda3\lib\site-packages)
WARNING: You are using pip version 21.3.1; however, version 22.1.1 is available.
You should consider upgrading via the 'c:\anaconda3\python.exe -m pip install --upgrade pip' command.

# Connecting to PostgreSQL Server

In [ ]:
from sqlalchemy import create_engine
engine = create_engine('postgresql://postgres:1234@localhost:5432/Citi_Bike')

## Write SQL Query to merge all the data

In [ ]:
query="""
SELECT * from jan_2020 union all
select * from feb_2020 union all
select * from march_2020 union all
select * from apr_2020 union all
select * from may_2020 union all
select * from jun_2020 union all
select * from july_2020 union all
select * from aug_2020 union all
select * from sep_2020 union all
select * from oct_2020 union all
select * from nov_2020 union all
select * from dec_2020"""
df = pd.read_sql_query(query,con=engine)
df

In [ ]:
df.head()

,tripduration,starttime,stoptime,start station id,start station name,start station latitude,start station longitude,end station id,end station name,end station latitude,end station longitude,bikeid,usertype,birth year,gender
0,789,2020-01-01 00:00:55.3900,2020-01-01 00:14:05.1470,504,1 Ave & E 16 St,40.732219,-73.981656,307,Canal St & Rutgers St,40.714275,-73.989900,30326,Subscriber,1992,1
1,1541,2020-01-01 00:01:08.1020,2020-01-01 00:26:49.1780,3423,West Drive & Prospect Park West,40.661063,-73.979453,3300,Prospect Park West & 8 St,40.665147,-73.976376,17105,Customer,1969,1
2,1464,2020-01-01 00:01:42.1400,2020-01-01 00:26:07.0110,3687,E 33 St & 1 Ave,40.743227,-73.974498,259,South St & Whitehall St,40.701221,-74.012342,40177,Subscriber,1963,1
3,592,2020-01-01 00:01:45.5610,2020-01-01 00:11:38.1550,346,Bank St & Hudson St,40.736529,-74.006180,490,8 Ave & W 33 St,40.751551,-73.993934,27690,Subscriber,1980,1
4,702,2020-01-01 00:01:45.7880,2020-01-01 00:13:28.2400,372,Franklin Ave & Myrtle Ave,40.694546,-73.958014,3637,Fulton St & Waverly Ave,40.683239,-73.965996,32583,Subscriber,1982,1

# Converting data to csv file

In [ ]:
df.to_csv('df_merged.csv',index=False)